ARG VERSION=stable

# Dev image
FROM nginx:${VERSION}-alpine as dev

# Copy nginx config
COPY --chown=root:root ./nginx.config /etc/nginx/conf.d/default.conf
RUN mkdir -p /var/www/html

# Prod image
FROM dev as prod

WORKDIR /var/www/html
COPY --chown=root:nginx ./index.php .

EXPOSE 80
