---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phpapp-config
  namespace: phpapp
data:
  DB_HOST: "mysql.phpapp.svc.cluster.local"
  DB_PORT: "3306"
  DB_USER: "root"
  DB_PASS: "BigOneZPassword1"
  DB_NAME: "mysql"
  